language: android

jdk: oraclejdk8

env:
  global:
    - MALLOC_ARENA_MAX=2

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-support
    - extra-android-m2repository

branches:
  only:
    - master

script:
  - ./gradlew :lyra-shared-test:build --continue -s
  - ./gradlew :lyra:build --continue -s
  - ./gradlew :lyra-coder-gson:build --continue -s
  - ./gradlew :sample:sample-java:assembleLocal --continue -s
  - ./gradlew :sample:sample-kotlin:assembleLocal --continue -s

sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache